version: '3.8'

services:
  junit-executor:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djava.security.manager=allow -Djava.security.policy=/app/security.policy
    volumes:
      - ./logs:/app/logs
      - /tmp:/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
