services:
  junit-executor:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
      - YANDEX_GPT_API_KEY=${YANDEX_GPT_API_KEY}
      - YANDEX_GPT_FOLDER_ID=${YANDEX_GPT_FOLDER_ID}
    volumes:
      - ./logs:/app/logs
      - /tmp:/tmp
    restart: unless-stopped
